// Generated by npm run build. Do not edit directly. Source entry: src/content/index.js
(() => {
  // src/content/constants.js
  var HOST_ID = "ai-translator-v2-root";
  var MAX_SELECTION_CHARS = 12e3;
  var MAX_PAGE_BLOCKS = 220;
  var PAGE_BATCH_SIZE = 14;
  var PAGE_BATCH_CHAR_LIMIT = 9e3;
  var PAGE_BATCH_CONCURRENCY = 2;
  var PAGE_SCAN_TIMEOUT_MS = 8e3;
  var BATCH_TIMEOUT_MS = 12e4;
  var PAGE_BLOCK_SELECTOR = [
    "article p",
    "main p",
    "[role='main'] p",
    "section p",
    ".content p",
    ".post p",
    ".article p",
    "h1",
    "h2",
    "h3",
    "h4",
    "blockquote",
    "dd",
    "dt",
    "article div",
    "main div",
    "[role='main'] div",
    "p",
    "li"
  ].join(",");

  // src/content/runtime.js
  function sendRuntimeMessage(message, timeoutMs = 0) {
    return new Promise((resolve) => {
      let settled = false;
      const finish = (value) => {
        if (!settled) {
          settled = true;
          resolve(value);
        }
      };
      if (timeoutMs > 0) {
        window.setTimeout(() => {
          finish({ ok: false, error: "\u8BF7\u6C42\u8D85\u65F6\u3002", timeout: true });
        }, timeoutMs);
      }
      chrome.runtime.sendMessage(message, (response) => {
        if (chrome.runtime.lastError) {
          finish({ ok: false, error: chrome.runtime.lastError.message });
          return;
        }
        finish(response);
      });
    });
  }
  function centeredRect() {
    return {
      left: Math.max(16, window.innerWidth / 2 - 180),
      bottom: Math.max(16, window.innerHeight / 2 - 80)
    };
  }
  function normalizeHostname(value) {
    return String(value || "").toLowerCase().replace(/^www\./, "");
  }
  function getPageUrlKey() {
    return `${location.origin}${location.pathname}${location.search}`;
  }
  function clamp(value, min, max) {
    return Math.min(Math.max(value, min), Math.max(min, max));
  }
  function toReadableError(error) {
    if (error instanceof Error) {
      return error.message;
    }
    return typeof error === "string" ? error : "\u53D1\u751F\u4E86\u672A\u77E5\u9519\u8BEF\u3002";
  }

  // src/content/text.js
  function cleanText(value) {
    const text = typeof value === "string" ? value.trim() : "";
    return text.length > MAX_SELECTION_CHARS ? text.slice(0, MAX_SELECTION_CHARS) : text;
  }
  function cleanPageText(value) {
    return String(value || "").replace(/\s+/g, " ").trim();
  }
  function hasTranslatableContent(text) {
    return /[A-Za-zÀ-ɏ぀-ヿ가-힯Ѐ-ӿ]/.test(text);
  }
  function getElementSourceText(element) {
    const stored = element.getAttribute("data-ai-translator-v2-source-text");
    if (stored) {
      return cleanPageText(stored);
    }
    const text = cleanPageText(Array.from(element.childNodes).filter((node) => {
      return !(node.nodeType === Node.ELEMENT_NODE && node instanceof HTMLElement && node.hasAttribute("data-ai-translator-v2-compact-result"));
    }).map((node) => node.textContent || "").join(" "));
    if (text) {
      element.setAttribute("data-ai-translator-v2-source-text", text);
    }
    return text;
  }
  function isSameMeaningText(originalText, translatedText) {
    const normalize = (value) => cleanPageText(value).toLowerCase().replace(/[^\p{L}\p{N}]+/gu, "");
    return normalize(originalText) === normalize(translatedText);
  }

  // src/content/ui-template.js
  function getUiTemplate() {
    return `
      <style>
        :host {
          all: initial;
          color-scheme: light;
          font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        }

        button {
          font: inherit;
        }

        .translate-button {
          align-items: center;
          background: #176b58;
          border: 1px solid rgba(255, 255, 255, 0.28);
          border-radius: 999px;
          box-shadow: 0 10px 24px rgba(20, 34, 31, 0.24);
          color: #ffffff;
          cursor: pointer;
          display: none;
          font-size: 14px;
          font-weight: 800;
          height: 34px;
          justify-content: center;
          line-height: 1;
          min-width: 34px;
          padding: 0 11px;
          position: fixed;
          z-index: 2147483647;
        }

        .translate-button:hover {
          background: #125546;
        }

        .panel {
          background: #ffffff;
          border: 1px solid #d8dedb;
          border-radius: 8px;
          box-shadow: 0 18px 44px rgba(24, 31, 29, 0.22);
          color: #1d2724;
          display: none;
          max-height: min(420px, calc(100vh - 32px));
          max-width: min(420px, calc(100vw - 32px));
          min-width: 280px;
          overflow: hidden;
          position: fixed;
          width: max-content;
          z-index: 2147483647;
        }

        .panel-header {
          align-items: center;
          background: #f5f7f4;
          border-bottom: 1px solid #e2e7e4;
          display: flex;
          gap: 8px;
          justify-content: space-between;
          padding: 9px 10px;
        }

        .title {
          color: #24302d;
          font-size: 12px;
          font-weight: 700;
          letter-spacing: 0;
        }

        .actions {
          display: flex;
          gap: 6px;
        }

        .icon-button {
          align-items: center;
          background: #ffffff;
          border: 1px solid #ced8d3;
          border-radius: 6px;
          color: #23312d;
          cursor: pointer;
          display: inline-flex;
          font-size: 12px;
          height: 28px;
          justify-content: center;
          line-height: 1;
          min-width: 28px;
          padding: 0 8px;
        }

        .icon-button:hover {
          border-color: #8aa49a;
        }

        .result {
          font-size: 14px;
          line-height: 1.55;
          max-height: 320px;
          overflow: auto;
          padding: 12px 13px;
          white-space: pre-wrap;
          word-break: break-word;
        }

        .status {
          color: #5d6b66;
          font-size: 12px;
          padding: 0 13px 12px;
        }

        .page-toast {
          align-items: center;
          backdrop-filter: blur(14px);
          background: rgba(22, 32, 29, 0.92);
          border: 1px solid rgba(255, 255, 255, 0.1);
          border-radius: 999px;
          bottom: 18px;
          box-shadow: 0 18px 44px rgba(11, 22, 18, 0.28);
          color: #ffffff;
          display: none;
          gap: 9px;
          left: 50%;
          max-width: min(560px, calc(100vw - 32px));
          padding: 7px 8px;
          position: fixed;
          transform: translateX(-50%);
          user-select: none;
          z-index: 2147483647;
        }

        .page-toast.is-positioned {
          bottom: auto;
          transform: none;
        }

        .page-toast.is-collapsed {
          max-width: min(240px, calc(100vw - 32px));
        }

        .page-toast.is-collapsed .toast-actions,
        .page-toast.is-collapsed .toast-text {
          display: none;
        }

        .page-toast.is-collapsed .toast-drag {
          display: inline-flex;
        }

        .toast-ring {
          align-items: center;
          background: conic-gradient(#7ee0c1 var(--progress, 0%), rgba(255, 255, 255, 0.18) 0);
          border: 0;
          border-radius: 999px;
          color: #ffffff;
          cursor: pointer;
          display: inline-flex;
          flex: 0 0 auto;
          font-size: 11px;
          font-weight: 800;
          height: 34px;
          justify-content: center;
          min-width: 34px;
          padding: 0;
          position: relative;
          width: 34px;
        }

        .toast-ring::before {
          background: #16201d;
          border-radius: inherit;
          content: "";
          inset: 4px;
          position: absolute;
        }

        .toast-ring span {
          position: relative;
        }

        .page-toast.is-paused .toast-ring {
          background: conic-gradient(#f6c76b var(--progress, 0%), rgba(255, 255, 255, 0.18) 0);
        }

        .page-toast.is-error .toast-ring {
          background: conic-gradient(#ef8b8b var(--progress, 0%), rgba(255, 255, 255, 0.18) 0);
        }

        .page-toast span {
          font-size: 13px;
          line-height: 1.4;
        }

        .toast-text {
          min-width: 0;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }

        .toast-actions {
          align-items: center;
          display: flex;
          gap: 7px;
        }

        .page-toast button {
          background: rgba(255, 255, 255, 0.12);
          border: 1px solid rgba(255, 255, 255, 0.18);
          border-radius: 999px;
          color: #ffffff;
          cursor: pointer;
          font-size: 12px;
          height: 28px;
          padding: 0 10px;
        }

        .page-toast .toast-drag {
          cursor: grab;
          font-size: 15px;
          min-width: 28px;
          padding: 0;
        }

        .page-toast .toast-drag:active {
          cursor: grabbing;
        }
      </style>
      <button class="translate-button" type="button" title="\u7FFB\u8BD1">\u8BD1</button>
      <section class="panel" role="dialog" aria-label="\u7FFB\u8BD1\u7ED3\u679C">
        <div class="panel-header">
          <div class="title">\u82B1\u8336\u7FFB\u8BD1\u5668</div>
          <div class="actions">
            <button class="icon-button copy" type="button" title="\u590D\u5236">\u590D\u5236</button>
            <button class="icon-button close" type="button" title="\u5173\u95ED">\u5173\u95ED</button>
          </div>
        </div>
        <div class="result"></div>
        <div class="status"></div>
      </section>
      <div class="page-toast is-collapsed" role="status">
        <button class="toast-ring" type="button" title="\u5C55\u5F00\u63A7\u5236\u5668"><span>0%</span></button>
        <button class="toast-drag" type="button" title="\u62D6\u52A8">\u22EE\u22EE</button>
        <span class="toast-text"></span>
        <button class="collapse-page-toast" type="button" title="\u6536\u8D77">\u6536\u8D77</button>
        <div class="toast-actions">
          <button class="dismiss-page-toast" type="button" title="\u9690\u85CF\u63A7\u5236\u5668">\u9690\u85CF</button>
          <button class="pause-page" type="button">\u6682\u505C</button>
          <button class="resume-page" type="button">\u7EE7\u7EED</button>
          <button class="clear-page" type="button">\u8FD8\u539F</button>
        </div>
      </div>
    `;
  }

  // src/content/page-scanner.js
  function collectTextBlocks(tracking) {
    const candidates = [
      ...Array.from(document.querySelectorAll(PAGE_BLOCK_SELECTOR)),
      ...collectVisibleTextContainers()
    ];
    const rankedCandidates = [];
    const seenElements = /* @__PURE__ */ new Set();
    let order = 0;
    for (const element of candidates) {
      if (seenElements.has(element)) {
        continue;
      }
      seenElements.add(element);
      if (isElementAlreadyQueued(element, tracking)) {
        continue;
      }
      if (!isTranslatableBlock(element)) {
        continue;
      }
      const text = cleanPageText(element.textContent);
      if (!text) {
        continue;
      }
      rankedCandidates.push({
        element,
        text,
        order,
        score: getViewportScore(element.getBoundingClientRect()),
        priority: getCandidatePriority(element)
      });
      order += 1;
    }
    rankedCandidates.sort((left, right) => {
      return left.score - right.score || right.priority - left.priority || left.order - right.order;
    });
    const blocks = [];
    for (const candidate of rankedCandidates) {
      if (blocks.length >= MAX_PAGE_BLOCKS) {
        break;
      }
      if (blocks.some((block) => block.contains(candidate.element) || candidate.element.contains(block))) {
        continue;
      }
      blocks.push(candidate.element);
    }
    return blocks;
  }
  function isElementAlreadyQueued(element, tracking) {
    if (tracking.translatedElements.has(element) || tracking.translatingElements.has(element)) {
      return true;
    }
    if (element.hasAttribute("data-ai-translator-v2-translated")) {
      return true;
    }
    if (element.parentElement?.closest("[data-ai-translator-v2-source-text]")) {
      return true;
    }
    return Boolean(element.closest("[data-ai-translator-v2-result], [data-ai-translator-v2-compact-result]"));
  }
  function getViewportScore(rect) {
    const viewportCenter = window.innerHeight * 0.45;
    const elementCenter = rect.top + rect.height / 2;
    const nearViewport = rect.bottom >= -window.innerHeight * 0.2 && rect.top <= window.innerHeight * 1.2;
    const distance = Math.abs(elementCenter - viewportCenter);
    return nearViewport ? distance : distance + window.innerHeight * 3;
  }
  function getCandidatePriority(element) {
    if (isCompactTextElement(element)) {
      return 3;
    }
    if (isHeadingElement(element)) {
      return 2;
    }
    return 1;
  }
  function waitForTextBlocks(tracking) {
    const startedAt = Date.now();
    return new Promise((resolve) => {
      const read = () => {
        const blocks = collectTextBlocks(tracking);
        if (blocks.length > 0 || Date.now() - startedAt > PAGE_SCAN_TIMEOUT_MS) {
          observer.disconnect();
          window.clearInterval(interval);
          resolve(blocks);
        }
      };
      const observer = new MutationObserver(read);
      observer.observe(document.documentElement, {
        childList: true,
        subtree: true,
        characterData: true
      });
      const interval = window.setInterval(read, 350);
      read();
    });
  }
  function collectVisibleTextContainers() {
    if (!document.body) {
      return [];
    }
    const walker = document.createTreeWalker(
      document.body,
      NodeFilter.SHOW_TEXT,
      {
        acceptNode(node2) {
          const text = cleanPageText(node2.textContent);
          if (text.length < 2 || !hasTranslatableContent(text)) {
            return NodeFilter.FILTER_REJECT;
          }
          const parent = node2.parentElement;
          if (!parent || shouldIgnoreElement(parent)) {
            return NodeFilter.FILTER_REJECT;
          }
          return NodeFilter.FILTER_ACCEPT;
        }
      }
    );
    const containers = [];
    const seen = /* @__PURE__ */ new Set();
    let node = walker.nextNode();
    while (node) {
      const container = findTextContainer(node.parentElement);
      if (container && !seen.has(container)) {
        seen.add(container);
        containers.push(container);
      }
      node = walker.nextNode();
    }
    return containers;
  }
  function findTextContainer(element) {
    let current = element;
    let best = element;
    while (current && current !== document.body && current !== document.documentElement) {
      if (shouldIgnoreElement(current)) {
        return null;
      }
      if (isCompactTextElement(current)) {
        return current;
      }
      const text = cleanPageText(current.textContent);
      if (text.length > 2400) {
        break;
      }
      best = current;
      if (isBlockLikeElement(current)) {
        break;
      }
      current = current.parentElement;
    }
    return best;
  }
  function isBlockLikeElement(element) {
    const tagName = element.tagName.toLowerCase();
    if (/^(p|li|dd|dt|blockquote|h[1-6])$/.test(tagName)) {
      return true;
    }
    const display = window.getComputedStyle(element).display;
    return display === "block" || display === "list-item";
  }
  function isTranslatableBlock(element) {
    if (!(element instanceof HTMLElement)) {
      return false;
    }
    if (shouldIgnoreElement(element)) {
      return false;
    }
    if (element.nextElementSibling?.hasAttribute("data-ai-translator-v2-result")) {
      return false;
    }
    const rect = element.getBoundingClientRect();
    const compact = isCompactTextElement(element);
    const minWidth = compact ? 16 : 80;
    const minHeight = compact ? 8 : 10;
    if (rect.width < minWidth || rect.height < minHeight) {
      return false;
    }
    const style = window.getComputedStyle(element);
    if (style.display === "none" || style.visibility === "hidden" || Number(style.opacity) === 0) {
      return false;
    }
    const text = cleanPageText(element.textContent);
    if (!hasTranslatableContent(text)) {
      return false;
    }
    if (text.length > (compact ? 160 : 3600)) {
      return false;
    }
    if (!compact && hasMeaningfulChildBlock(element, text)) {
      return false;
    }
    if (compact) {
      return text.length >= 2;
    }
    return isHeadingElement(element) ? text.length >= 4 : text.length >= 6;
  }
  function shouldIgnoreElement(element) {
    return Boolean(
      element.closest(`#${HOST_ID}`) || element.closest("[data-ai-translator-v2-result]") || element.closest("nav, header, footer, script, style, noscript, textarea, input, select, option, pre, code, [contenteditable='true']") || element.matches("summary, svg, canvas, img, video, audio, [role='navigation'], [aria-hidden='true']")
    );
  }
  function hasMeaningfulChildBlock(element, ownText) {
    const tagName = element.tagName.toLowerCase();
    if (/^(p|li|dd|dt|blockquote|h[1-6])$/.test(tagName)) {
      return false;
    }
    const childBlocks = Array.from(element.children).filter((child) => {
      if (!(child instanceof HTMLElement) || shouldIgnoreElement(child)) {
        return false;
      }
      if (!isBlockLikeElement(child) && !isCompactTextElement(child)) {
        return false;
      }
      const childText = cleanPageText(child.textContent);
      if (isCompactTextElement(child)) {
        return childText.length >= 2 && childText.length < ownText.length * 0.92;
      }
      return childText.length >= 12 && childText.length < ownText.length * 0.92;
    });
    return childBlocks.length > 1;
  }
  function isHeadingElement(element) {
    return /^h[1-6]$/i.test(element.tagName);
  }
  function getTranslationMode(element) {
    return isCompactTextElement(element) ? "compact" : "block";
  }
  function isCompactTextElement(element) {
    if (!(element instanceof HTMLElement) || isHeadingElement(element)) {
      return false;
    }
    const tagName = element.tagName.toLowerCase();
    if (/^(html|body|main|article|section|ul|ol|table|tbody|thead|tr)$/.test(tagName)) {
      return false;
    }
    if (element.children.length > 4) {
      return false;
    }
    const text = cleanPageText(element.textContent);
    if (text.length < 2 || text.length > 80 || !hasTranslatableContent(text)) {
      return false;
    }
    const rect = element.getBoundingClientRect();
    if (rect.width > 420 || rect.height > 120) {
      return false;
    }
    const style = window.getComputedStyle(element);
    if (!["inline", "inline-block", "inline-flex", "flex", "block"].includes(style.display)) {
      return false;
    }
    const className = String(element.className || "");
    const classHint = /\b(tag|chip|pill|badge|skill|keyword|label|category|stack|technology|tech)\b/i.test(className);
    const roleHint = /^(button|link|listitem|tab)$/i.test(element.getAttribute("role") || "");
    const boxHint = hasBoxStyling(element, style);
    const parentLayoutHint = hasCompactParentLayout(element);
    const controlHint = tagName === "button";
    return classHint || roleHint || boxHint || parentLayoutHint || controlHint;
  }
  function hasBoxStyling(element, style) {
    const horizontalPadding = parseFloat(style.paddingLeft || "0") + parseFloat(style.paddingRight || "0");
    const hasBorder = parseFloat(style.borderLeftWidth || "0") + parseFloat(style.borderRightWidth || "0") > 0;
    const hasRadius = parseFloat(style.borderTopLeftRadius || "0") > 0;
    const hasBackground = style.backgroundColor && !/rgba?\(0,\s*0,\s*0,\s*0\)|transparent/i.test(style.backgroundColor);
    return horizontalPadding >= 8 || hasBorder || hasRadius || hasBackground || element.matches("button");
  }
  function hasCompactParentLayout(element) {
    const parent = element.parentElement;
    if (!parent) {
      return false;
    }
    const parentStyle = window.getComputedStyle(parent);
    if (!["flex", "inline-flex", "grid", "inline-grid"].includes(parentStyle.display) && parentStyle.flexWrap !== "wrap") {
      return false;
    }
    const siblings = Array.from(parent.children).filter((child) => {
      if (!(child instanceof HTMLElement) || child === element || shouldIgnoreElement(child)) {
        return false;
      }
      const text = cleanPageText(child.textContent);
      return text.length >= 2 && text.length <= 80 && hasTranslatableContent(text);
    });
    return siblings.length > 0;
  }

  // src/content/page-renderer.js
  function setTranslationResult(job, text, loading, isError = false) {
    if (job.mode === "compact") {
      setCompactResult(job.block, text, loading, isError);
      return;
    }
    setBlockResult(job.block, text, loading, isError);
    if (!loading && !isError) {
      job.block.setAttribute("data-ai-translator-v2-translated", "true");
    }
  }
  function removeTranslationResult(job) {
    job.block.removeAttribute("data-ai-translator-v2-pending");
    if (job.mode === "compact") {
      const compactNode = job.block.querySelector(":scope > [data-ai-translator-v2-compact-result]");
      if (compactNode) {
        compactNode.remove();
      }
      return;
    }
    const node = job.block.nextElementSibling;
    if (node?.hasAttribute("data-ai-translator-v2-result")) {
      node.remove();
    }
  }
  function setBlockResult(anchor, text, loading, isError = false) {
    let node = anchor.querySelector(":scope > [data-ai-translator-v2-result]");
    if (!node) {
      node = anchor.nextElementSibling;
      if (node && !node.hasAttribute("data-ai-translator-v2-result")) {
        node = null;
      }
    }
    if (!loading && !isError && isSameMeaningText(getElementSourceText(anchor), text)) {
      if (node) {
        node.remove();
      }
      return;
    }
    if (!node) {
      node = document.createElement("div");
      node.setAttribute("data-ai-translator-v2-result", "true");
      const insertStrategy = getInsertStrategy(anchor);
      if (insertStrategy === "inside") {
        anchor.appendChild(node);
      } else if (insertStrategy === "after-parent") {
        const parent = findTranslatableParent(anchor);
        if (parent && parent !== anchor) {
          parent.insertAdjacentElement("afterend", node);
        } else {
          anchor.insertAdjacentElement("afterend", node);
        }
      } else {
        anchor.insertAdjacentElement("afterend", node);
      }
    }
    node.className = [
      "ai-translator-v2-inline-result",
      loading ? "is-loading" : "",
      isError ? "is-error" : ""
    ].filter(Boolean).join(" ");
    node.textContent = text;
  }
  function getInsertStrategy(element) {
    if (element.tagName === "DIV" && element.hasAttribute("dir")) {
      const article = element.closest("article");
      if (article && window.location.hostname.includes("twitter.com") || window.location.hostname === "x.com") {
        return "after-parent";
      }
    }
    if (element.tagName === "ARTICLE") return "inside";
    if (element.classList.toString().match(/tweet|post|status/i)) return "inside";
    if (["DIV", "SECTION", "MAIN"].includes(element.tagName)) {
      const childElements = Array.from(element.children).filter(
        (c) => !c.hasAttribute("data-ai-translator-v2-result") && !c.hasAttribute("data-ai-translator-v2-compact-result")
      );
      if (childElements.length > 3) return "inside";
    }
    return "after";
  }
  function findTranslatableParent(element) {
    let current = element.parentElement;
    let depth = 0;
    while (current && depth < 3) {
      if (current.hasAttribute("dir") || current.hasAttribute("lang")) {
        return current;
      }
      if (current.tagName === "ARTICLE") {
        return element;
      }
      current = current.parentElement;
      depth++;
    }
    return element;
  }
  function setCompactResult(anchor, text, loading, isError = false) {
    if (loading) {
      anchor.setAttribute("data-ai-translator-v2-pending", "true");
      return;
    }
    anchor.removeAttribute("data-ai-translator-v2-pending");
    const originalText = getElementSourceText(anchor);
    let node = anchor.querySelector(":scope > [data-ai-translator-v2-compact-result]");
    if (!node) {
      node = document.createElement("span");
      node.setAttribute("data-ai-translator-v2-compact-result", "true");
      anchor.appendChild(node);
    }
    node.className = [
      "ai-translator-v2-compact-result",
      isError ? "is-error" : ""
    ].filter(Boolean).join(" ");
    if (!isError && isSameMeaningText(originalText, text)) {
      node.remove();
      return;
    }
    node.textContent = text;
  }
  function removePageTranslationMarkup() {
    document.querySelectorAll("[data-ai-translator-v2-result]").forEach((node) => node.remove());
    document.querySelectorAll("[data-ai-translator-v2-compact-result]").forEach((node) => node.remove());
    document.querySelectorAll("[data-ai-translator-v2-pending]").forEach((node) => {
      node.removeAttribute("data-ai-translator-v2-pending");
    });
    document.querySelectorAll("[data-ai-translator-v2-source-text]").forEach((node) => {
      node.removeAttribute("data-ai-translator-v2-source-text");
    });
  }
  function clearTransientPageErrors(isTransientTranslationError) {
    document.querySelectorAll("[data-ai-translator-v2-result], [data-ai-translator-v2-compact-result]").forEach((node) => {
      if (isTransientTranslationError(node.textContent || "")) {
        node.remove();
      }
    });
    document.querySelectorAll("[data-ai-translator-v2-pending]").forEach((node) => {
      node.removeAttribute("data-ai-translator-v2-pending");
    });
  }
  function resetPendingPageJobs() {
    document.querySelectorAll("[data-ai-translator-v2-pending]").forEach((node) => {
      node.removeAttribute("data-ai-translator-v2-pending");
    });
    document.querySelectorAll("[data-ai-translator-v2-result].is-loading").forEach((node) => node.remove());
  }
  function ensureInlineStyles() {
    if (document.getElementById("ai-translator-v2-inline-style")) {
      return;
    }
    const style = document.createElement("style");
    style.id = "ai-translator-v2-inline-style";
    style.textContent = `
    .ai-translator-v2-inline-result {
      /* \u7EE7\u627F\u539F\u7F51\u7AD9\u6837\u5F0F\uFF0C\u770B\u8D77\u6765\u50CF\u539F\u751F\u5185\u5BB9 */
      color: inherit;
      font-family: inherit;
      font-size: inherit;
      line-height: inherit;
      margin: 0;
      padding: 0;
      white-space: pre-wrap;
      opacity: 0.75;
      font-style: italic;
    }

    .ai-translator-v2-inline-result.is-loading {
      opacity: 0.5;
    }

    .ai-translator-v2-inline-result.is-error {
      color: #d73a49;
      opacity: 0.7;
    }

    [data-ai-translator-v2-pending="true"] {
      /* \u65E0\u9AD8\u4EAE */
    }

    .ai-translator-v2-compact-result {
      /* \u7D27\u51D1\u6A21\u5F0F\uFF1A\u76F4\u63A5\u8DDF\u5728\u539F\u6587\u540E\uFF0C\u7528\u659C\u6760\u5206\u9694 */
      color: inherit;
      display: inline;
      font-family: inherit;
      font-size: 0.95em;
      font-weight: inherit;
      margin-left: 0.3em;
      white-space: normal;
      opacity: 0.7;
    }

    .ai-translator-v2-compact-result::before {
      content: " / ";
      color: currentColor;
      opacity: 0.4;
    }

    .ai-translator-v2-compact-result.is-error {
      color: #d73a49;
    }

    html[data-ai-translator-v2-hidden] .ai-translator-v2-inline-result,
    html[data-ai-translator-v2-hidden] .ai-translator-v2-compact-result {
      display: none !important;
    }
  `;
    document.head.appendChild(style);
  }

  // src/content/index.js
  (() => {
    if (window.__AI_TRANSLATOR_V2_CONTENT_SCRIPT_LOADED__) {
      return;
    }
    window.__AI_TRANSLATOR_V2_CONTENT_SCRIPT_LOADED__ = true;
    let host = null;
    let shadow = null;
    let button = null;
    let panel = null;
    let resultNode = null;
    let statusNode = null;
    let pageToast = null;
    let pageToastText = null;
    let activeText = "";
    let autoSelectionButton = true;
    let targetLanguage = "Chinese (Simplified)";
    let sitePreferences = {};
    let lastSelectionRect = null;
    let hideTimer = 0;
    let pageObserver = null;
    let pageTranslateTimer = 0;
    let pageScanPromise = null;
    let pageUrlKey = getPageUrlKey();
    let pageToastDismissed = false;
    let pageToastCollapsed = false;
    let pageToastPosition = null;
    let pageToastDrag = null;
    let jobCounter = 0;
    let pageSessionId = 0;
    let pageTranslationsHidden = false;
    let countedElements = /* @__PURE__ */ new WeakSet();
    let translatedElements = /* @__PURE__ */ new WeakSet();
    let translatingElements = /* @__PURE__ */ new WeakSet();
    let pageState = {
      enabled: false,
      busy: false,
      cancelled: false,
      paused: false,
      translated: 0,
      total: 0,
      discovered: 0
    };
    init();
    function init() {
      loadSettings().then((settings) => {
        const preference = settings.sitePreferences?.[normalizeHostname(location.hostname)];
        if (preference === "always") {
          window.setTimeout(() => translatePage(), 900);
        }
      });
      document.addEventListener("mouseup", handleSelectionEvent, true);
      document.addEventListener("keyup", handleSelectionEvent, true);
      document.addEventListener("scroll", handlePageScroll, true);
      document.addEventListener("visibilitychange", handleVisibilityChange);
      installUrlWatcher();
      chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
        if (message?.type === "AI_TRANSLATOR_CONTEXT_TRANSLATE") {
          const text = cleanText(message.text || getSelectedText());
          startTranslation(text);
          sendResponse({ ok: true });
          return false;
        }
        if (message?.type === "AI_TRANSLATOR_TRANSLATE_PAGE") {
          translatePage().then((status) => sendResponse({ ok: true, status })).catch((error) => sendResponse({ ok: false, error: toReadableError(error) }));
          return true;
        }
        if (message?.type === "AI_TRANSLATOR_CLEAR_PAGE_TRANSLATION") {
          clearPageTranslations();
          sendResponse({ ok: true });
          return false;
        }
        if (message?.type === "AI_TRANSLATOR_GET_PAGE_STATUS") {
          sendResponse({ ok: true, status: getPageStatus() });
          return false;
        }
        if (message?.type === "AI_TRANSLATOR_TOGGLE_PAGE_VISIBILITY") {
          sendResponse({ ok: true, hidden: togglePageTranslationsHidden() });
          return false;
        }
        return false;
      });
      chrome.storage.onChanged.addListener((changes, areaName) => {
        if (areaName !== "local") {
          return;
        }
        if (changes.autoSelectionButton) {
          autoSelectionButton = changes.autoSelectionButton.newValue !== false;
        }
        if (changes.targetLanguage) {
          targetLanguage = changes.targetLanguage.newValue || "Chinese (Simplified)";
        }
        if (changes.sitePreferences) {
          sitePreferences = changes.sitePreferences.newValue || {};
        }
      });
    }
    async function loadSettings() {
      const response = await sendRuntimeMessage({ type: "AI_TRANSLATOR_GET_SETTINGS" });
      if (!response?.ok) {
        return {};
      }
      autoSelectionButton = response.settings.autoSelectionButton !== false;
      targetLanguage = response.settings.targetLanguage || "Chinese (Simplified)";
      sitePreferences = response.settings.sitePreferences || {};
      return response.settings;
    }
    function handleSelectionEvent(event) {
      if (!autoSelectionButton || isInsideTranslator(event.target)) {
        return;
      }
      window.clearTimeout(hideTimer);
      window.setTimeout(() => {
        const text = cleanText(getSelectedText());
        const rect = getSelectionRect();
        if (!text || !rect) {
          hideButton();
          return;
        }
        activeText = text;
        lastSelectionRect = rect;
        showButton(rect);
      }, 20);
    }
    function handlePageScroll() {
      hideButtonSoon();
      scheduleContinuousPageTranslation(260);
    }
    function handleVisibilityChange() {
      if (!pageState.enabled) {
        return;
      }
      if (document.hidden) {
        window.clearTimeout(pageTranslateTimer);
        pageTranslateTimer = 0;
        const host2 = document.getElementById(HOST_ID);
        if (host2) {
          host2.remove();
        }
        pageState.paused = false;
        pageState.enabled = false;
        return;
      }
    }
    function installUrlWatcher() {
      const notifyUrlChange = () => {
        window.setTimeout(handleUrlChange, 60);
      };
      const originalPushState = history.pushState;
      const originalReplaceState = history.replaceState;
      history.pushState = function pushState(...args) {
        const result = originalPushState.apply(this, args);
        notifyUrlChange();
        return result;
      };
      history.replaceState = function replaceState(...args) {
        const result = originalReplaceState.apply(this, args);
        notifyUrlChange();
        return result;
      };
      window.addEventListener("popstate", notifyUrlChange);
      window.addEventListener("hashchange", notifyUrlChange);
      window.setInterval(handleUrlChange, 1200);
    }
    function handleUrlChange() {
      const nextKey = getPageUrlKey();
      if (nextKey === pageUrlKey) {
        return;
      }
      pageUrlKey = nextKey;
      resetPageTranslationForNavigation();
    }
    function resetPageTranslationForNavigation() {
      const shouldContinue = false;
      const wasDismissed = pageToastDismissed;
      pageSessionId += 1;
      stopContinuousPageTranslation();
      removePageTranslationMarkup();
      countedElements = /* @__PURE__ */ new WeakSet();
      translatedElements = /* @__PURE__ */ new WeakSet();
      translatingElements = /* @__PURE__ */ new WeakSet();
      pageState = {
        enabled: shouldContinue,
        busy: false,
        cancelled: false,
        paused: false,
        translated: 0,
        total: 0,
        discovered: 0
      };
      if (shouldContinue) {
        startContinuousPageTranslation();
        pageToastDismissed = wasDismissed;
        showPageToast("\u5DF2\u5207\u6362\u5230\u65B0\u9875\u9762\uFF0C\u7FFB\u8BD1\u8FDB\u5EA6\u5DF2\u91CD\u7F6E\u3002", false);
        scheduleContinuousPageTranslation(900);
        return;
      }
      hidePageToast();
    }
    function getSelectedText() {
      const selection = window.getSelection();
      if (!selection || selection.rangeCount === 0) {
        return "";
      }
      return selection.toString();
    }
    function getSelectionRect() {
      const selection = window.getSelection();
      if (!selection || selection.rangeCount === 0 || selection.isCollapsed) {
        return null;
      }
      const range = selection.getRangeAt(0);
      const rects = Array.from(range.getClientRects()).filter((rect) => {
        return rect.width > 0 && rect.height > 0;
      });
      return rects[rects.length - 1] || range.getBoundingClientRect();
    }
    function ensureDom() {
      if (host && shadow) {
        return;
      }
      host = document.getElementById(HOST_ID);
      if (!host) {
        host = document.createElement("div");
        host.id = HOST_ID;
        document.documentElement.appendChild(host);
      }
      shadow = getTranslatorShadowRoot();
      shadow.innerHTML = getUiTemplate();
      button = shadow.querySelector(".translate-button");
      panel = shadow.querySelector(".panel");
      resultNode = shadow.querySelector(".result");
      statusNode = shadow.querySelector(".status");
      pageToast = shadow.querySelector(".page-toast");
      pageToastText = pageToast.querySelector(".toast-text");
      button.addEventListener("mousedown", (event) => event.preventDefault());
      button.addEventListener("click", () => startTranslation(activeText));
      shadow.querySelector(".close").addEventListener("click", hidePanel);
      shadow.querySelector(".copy").addEventListener("click", copyResult);
      shadow.querySelector(".pause-page").addEventListener("click", pausePageTranslation);
      shadow.querySelector(".resume-page").addEventListener("click", resumePageTranslation);
      shadow.querySelector(".clear-page").addEventListener("click", clearPageTranslations);
      shadow.querySelector(".collapse-page-toast").addEventListener("click", togglePageToastCollapsed);
      shadow.querySelector(".toast-ring").addEventListener("click", togglePageToastCollapsed);
      shadow.querySelector(".dismiss-page-toast").addEventListener("click", dismissPageToast);
      shadow.querySelector(".toast-drag").addEventListener("pointerdown", startPageToastDrag);
    }
    function getTranslatorShadowRoot() {
      if (host.shadowRoot) {
        return host.shadowRoot;
      }
      try {
        return host.attachShadow({ mode: "open" });
      } catch (error) {
        host.remove();
        host = document.createElement("div");
        host.id = HOST_ID;
        document.documentElement.appendChild(host);
        return host.attachShadow({ mode: "open" });
      }
    }
    function showButton(rect) {
      ensureDom();
      const x = clamp(rect.right + 8, 8, window.innerWidth - 52);
      const y = clamp(rect.bottom + 8, 8, window.innerHeight - 42);
      button.style.left = `${x}px`;
      button.style.top = `${y}px`;
      button.style.display = "inline-flex";
    }
    function hideButtonSoon() {
      window.clearTimeout(hideTimer);
      hideTimer = window.setTimeout(hideButton, 120);
    }
    function hideButton() {
      if (button) {
        button.style.display = "none";
      }
    }
    function showPanel(rect) {
      ensureDom();
      const width = Math.min(420, window.innerWidth - 32);
      const x = clamp(rect.left, 16, window.innerWidth - width - 16);
      const y = clamp(rect.bottom + 12, 16, window.innerHeight - 170);
      panel.style.width = `${width}px`;
      panel.style.left = `${x}px`;
      panel.style.top = `${y}px`;
      panel.style.display = "block";
    }
    function hidePanel() {
      if (panel) {
        panel.style.display = "none";
      }
    }
    async function startTranslation(text) {
      const content = cleanText(text);
      if (!content) {
        return;
      }
      ensureDom();
      hideButton();
      showPanel(lastSelectionRect || centeredRect());
      resultNode.textContent = "\u6B63\u5728\u7FFB\u8BD1...";
      statusNode.textContent = "";
      const response = await sendRuntimeMessage({
        type: "AI_TRANSLATOR_TRANSLATE_TEXT",
        text: content
      });
      if (!response?.ok) {
        resultNode.textContent = "\u7FFB\u8BD1\u5931\u8D25\u3002";
        statusNode.textContent = response?.error || "\u53D1\u751F\u4E86\u672A\u77E5\u9519\u8BEF\u3002";
        return;
      }
      resultNode.textContent = response.translation;
      statusNode.textContent = "\u5DF2\u5B8C\u6210";
    }
    async function translatePage() {
      ensureDom();
      ensureInlineStyles();
      clearTransientPageErrors(isTransientTranslationError);
      pageTranslationsHidden = false;
      document.documentElement.removeAttribute("data-ai-translator-v2-hidden");
      pageToastDismissed = false;
      pageToastCollapsed = true;
      applyPageToastState();
      if (pageState.paused || pageState.cancelled) {
        return resumePageTranslation();
      }
      const wasEnabled = pageState.enabled;
      pageState.enabled = true;
      pageState.cancelled = false;
      pageState.paused = false;
      if (!wasEnabled) {
        pageSessionId += 1;
      }
      startContinuousPageTranslation();
      if (pageState.busy || pageScanPromise) {
        showPageToast(`\u9875\u9762\u7FFB\u8BD1\u5DF2\u5F00\u542F\uFF0C\u5DF2\u5B8C\u6210 ${pageState.translated}/${pageState.total}\uFF0C\u6EDA\u52A8\u540E\u4F1A\u7EE7\u7EED\u3002`, true);
        return getPageStatus();
      }
      runPageScan({ wait: true });
      showPageToast("\u5DF2\u5F00\u542F\u9875\u9762\u7FFB\u8BD1\uFF0C\u8BD1\u6587\u4F1A\u5206\u6279\u51FA\u73B0\uFF1B\u7EE7\u7EED\u6EDA\u52A8\u4F1A\u81EA\u52A8\u7FFB\u8BD1\u65B0\u5185\u5BB9\u3002", true);
      return getPageStatus();
    }
    async function scanAndTranslateMore({ wait = false } = {}) {
      if (pageState.busy || pageState.cancelled || pageState.paused || !pageState.enabled) {
        return getPageStatus();
      }
      if (document.hidden) {
        return getPageStatus();
      }
      pageState.busy = true;
      if (wait) {
        showPageToast("\u6B63\u5728\u626B\u63CF\u9875\u9762\u6B63\u6587...", true);
      }
      try {
        const tracking = { translatedElements, translatingElements };
        const blocks = wait ? await waitForTextBlocks(tracking) : collectTextBlocks(tracking);
        const jobs = buildTranslationJobs(blocks);
        if (jobs.length === 0) {
          if (wait && pageState.translated === 0) {
            showPageToast("\u9875\u9762\u7FFB\u8BD1\u5DF2\u5F00\u542F\uFF0C\u6B63\u5728\u7B49\u5F85\u6B63\u6587\u6216\u6EDA\u52A8\u52A0\u8F7D\u7684\u65B0\u5185\u5BB9\u3002", false);
          }
          return getPageStatus();
        }
        const newJobCount = countNewPageJobs(jobs);
        pageState = {
          ...pageState,
          cancelled: false,
          discovered: pageState.discovered + newJobCount,
          total: pageState.total + newJobCount
        };
        showPageToast(
          newJobCount > 0 ? `\u53D1\u73B0 ${newJobCount} \u4E2A\u65B0\u6587\u672C\u5757\uFF0C\u6B63\u5728\u7FFB\u8BD1...` : `\u6B63\u5728\u8865\u8BD1 ${jobs.length} \u4E2A\u6587\u672C\u5757...`,
          true
        );
        jobs.forEach((job) => {
          translatingElements.add(job.block);
          setTranslationResult(job, "\u7B49\u5F85\u7FFB\u8BD1...", true);
        });
        await translatePageBatches(jobs);
        if (pageState.paused) {
          showPageToast(`\u5DF2\u6682\u505C\uFF0C\u5B8C\u6210 ${pageState.translated}/${pageState.total}\u3002\u70B9\u7EE7\u7EED\u53EF\u63A5\u7740\u7FFB\u3002`, false, { force: true });
        } else if (pageState.cancelled) {
          showPageToast(`\u5DF2\u505C\u6B62\uFF0C\u5B8C\u6210 ${pageState.translated}/${pageState.total}\u3002`, false);
        } else {
          showPageToast(`\u5DF2\u7FFB\u8BD1 ${pageState.translated}/${pageState.total}\uFF0C\u6EDA\u52A8\u540E\u4F1A\u7EE7\u7EED\u3002`, false);
          scheduleContinuousPageTranslation(900);
        }
        return getPageStatus();
      } finally {
        pageState.busy = false;
      }
    }
    function buildTranslationJobs(blocks) {
      return blocks.filter((block) => !translatedElements.has(block) && !translatingElements.has(block)).map((block) => ({
        id: makeJobId(),
        sessionId: pageSessionId,
        block,
        mode: getTranslationMode(block),
        text: getElementSourceText(block)
      })).filter((job) => job.text && !isProbablyAlreadyTranslated(job.text));
    }
    function countNewPageJobs(jobs) {
      let count = 0;
      for (const job of jobs) {
        if (countedElements.has(job.block)) {
          continue;
        }
        countedElements.add(job.block);
        count += 1;
      }
      return count;
    }
    function makeJobId() {
      jobCounter += 1;
      return `p${Date.now().toString(36)}-${jobCounter}`;
    }
    function isProbablyAlreadyTranslated(text) {
      const cleaned = cleanPageText(text);
      if (!cleaned) {
        return true;
      }
      if (!isChineseTargetLanguage()) {
        return false;
      }
      const cjkCount = (cleaned.match(/[\u3400-\u9fff]/g) || []).length;
      const latinCount = (cleaned.match(/[A-Za-z]/g) || []).length;
      return cjkCount >= 2 && cjkCount > latinCount;
    }
    function isChineseTargetLanguage() {
      return /Chinese|中文|汉语|漢語/i.test(targetLanguage || "");
    }
    function chunkTranslationJobs(jobs, maxItems, maxChars) {
      const chunks = [];
      let chunk = [];
      let charCount = 0;
      for (const job of jobs) {
        const textLength = job.text.length;
        if (chunk.length > 0 && (chunk.length >= maxItems || charCount + textLength > maxChars)) {
          chunks.push(chunk);
          chunk = [];
          charCount = 0;
        }
        chunk.push(job);
        charCount += textLength;
      }
      if (chunk.length > 0) {
        chunks.push(chunk);
      }
      return chunks;
    }
    async function translatePageBatches(jobs) {
      const batches = chunkTranslationJobs(jobs, PAGE_BATCH_SIZE, PAGE_BATCH_CHAR_LIMIT);
      let nextBatchIndex = 0;
      const runWorker = async () => {
        while (!pageState.cancelled && !pageState.paused && nextBatchIndex < batches.length) {
          const batch = batches[nextBatchIndex];
          nextBatchIndex += 1;
          await translatePageBatch(batch);
        }
      };
      const workers = Array.from(
        { length: Math.min(PAGE_BATCH_CONCURRENCY, batches.length) },
        () => runWorker()
      );
      await Promise.all(workers);
    }
    async function translatePageBatch(batch) {
      const activeBatch = batch.filter((job) => job.sessionId === pageSessionId);
      if (activeBatch.length === 0 || pageState.cancelled || pageState.paused) {
        return;
      }
      activeBatch.forEach((job) => setTranslationResult(job, "\u6B63\u5728\u7FFB\u8BD1...", true));
      showPageToast(`\u6B63\u5728\u7FFB\u8BD1 ${pageState.translated}/${pageState.total}`, true);
      const response = await sendRuntimeMessage({
        type: "AI_TRANSLATOR_TRANSLATE_BATCH",
        items: activeBatch.map((job) => ({ id: job.id, text: job.text }))
      }, BATCH_TIMEOUT_MS);
      if (!response?.ok) {
        const errorMessage = response?.error || "\u7FFB\u8BD1\u5931\u8D25\u3002";
        if (response?.timeout || isTransientTranslationError(errorMessage)) {
          activeBatch.forEach((job) => {
            removeTranslationResult(job);
            translatingElements.delete(job.block);
          });
          showPageToast(
            response?.timeout ? "\u8FD9\u6279\u8BF7\u6C42\u8D85\u65F6\uFF0C\u5DF2\u91CD\u65B0\u6392\u961F\uFF1B\u4E0D\u7528\u5237\u65B0\u9875\u9762\u3002" : "\u63A5\u53E3\u8FBE\u5230\u5E76\u53D1\u6216\u9650\u6D41\u4E0A\u9650\uFF0C\u5DF2\u653E\u6162\u5E76\u7A0D\u540E\u91CD\u8BD5\uFF1B\u4E0D\u7528\u5237\u65B0\u9875\u9762\u3002",
            false
          );
          scheduleContinuousPageTranslation(response?.timeout ? 2200 : 6500);
          return;
        }
        activeBatch.forEach((job) => {
          if (job.sessionId !== pageSessionId) {
            return;
          }
          setTranslationResult(job, errorMessage, false, true);
          translatingElements.delete(job.block);
        });
        if (pageState.translated === 0 && isBlockingTranslationError(errorMessage)) {
          showPageToast(errorMessage, false, { error: true, force: true });
          throw new Error(errorMessage);
        }
        return;
      }
      const translatedById = new Map(
        (response.items || []).map((item) => [String(item.id), item.translation])
      );
      for (const job of activeBatch) {
        if (pageState.cancelled || pageState.paused || job.sessionId !== pageSessionId) {
          return;
        }
        const translation = translatedById.get(job.id);
        if (!translation) {
          setTranslationResult(job, "\u8FD9\u4E00\u6BB5\u6CA1\u6709\u8FD4\u56DE\u8BD1\u6587\u3002", false, true);
          translatingElements.delete(job.block);
          continue;
        }
        setTranslationResult(job, translation, false);
        translatingElements.delete(job.block);
        translatedElements.add(job.block);
        pageState.translated += 1;
      }
      showPageToast(`\u6B63\u5728\u7FFB\u8BD1 ${pageState.translated}/${pageState.total}`, true);
    }
    function isBlockingTranslationError(message) {
      return /API Key|API 地址|401|403|unauthorized|forbidden|余额|额度|模型|model/i.test(message);
    }
    function isTransientTranslationError(message) {
      return /429|503|并发|频率|限流|rate.?limit|too many requests|繁忙|稍后/i.test(message || "");
    }
    function clearPageTranslations() {
      pageTranslationsHidden = false;
      document.documentElement.removeAttribute("data-ai-translator-v2-hidden");
      pageState.cancelled = true;
      pageState.enabled = false;
      pageSessionId += 1;
      stopContinuousPageTranslation();
      removePageTranslationMarkup();
      countedElements = /* @__PURE__ */ new WeakSet();
      translatedElements = /* @__PURE__ */ new WeakSet();
      translatingElements = /* @__PURE__ */ new WeakSet();
      pageState = {
        enabled: false,
        busy: false,
        cancelled: false,
        paused: false,
        translated: 0,
        total: 0,
        discovered: 0
      };
      showPageToast("\u5DF2\u8FD8\u539F\u5F53\u524D\u9875\u9762\u3002", false, { force: true });
    }
    function pausePageTranslation() {
      pageState.paused = true;
      pageState.cancelled = false;
      pageState.enabled = true;
      pageSessionId += 1;
      stopContinuousPageTranslation();
      translatingElements = /* @__PURE__ */ new WeakSet();
      resetPendingPageJobs();
      showPageToast(`\u5DF2\u6682\u505C\uFF0C\u5B8C\u6210 ${pageState.translated}/${pageState.total}\u3002\u70B9\u7EE7\u7EED\u63A5\u7740\u7FFB\u3002`, false, { force: true });
    }
    async function resumePageTranslation() {
      ensureDom();
      ensureInlineStyles();
      clearTransientPageErrors(isTransientTranslationError);
      translatingElements = /* @__PURE__ */ new WeakSet();
      resetPendingPageJobs();
      pageTranslationsHidden = false;
      document.documentElement.removeAttribute("data-ai-translator-v2-hidden");
      pageToastDismissed = false;
      pageState.enabled = true;
      pageState.cancelled = false;
      pageState.paused = false;
      pageSessionId += 1;
      startContinuousPageTranslation();
      showPageToast(`\u7EE7\u7EED\u7FFB\u8BD1\uFF0C\u5DF2\u5B8C\u6210 ${pageState.translated}/${pageState.total}\u3002`, true, { force: true });
      runPageScan({ wait: false });
      return getPageStatus();
    }
    function getPageStatus() {
      return {
        enabled: pageState.enabled,
        busy: pageState.busy,
        paused: pageState.paused,
        translated: pageState.translated,
        total: pageState.total,
        discovered: pageState.discovered,
        hidden: pageTranslationsHidden
      };
    }
    function togglePageTranslationsHidden() {
      setPageTranslationsHidden(!pageTranslationsHidden);
      return pageTranslationsHidden;
    }
    function setPageTranslationsHidden(hidden) {
      pageTranslationsHidden = hidden;
      document.documentElement.toggleAttribute("data-ai-translator-v2-hidden", hidden);
      if (hidden) {
        window.clearTimeout(pageTranslateTimer);
        pageTranslateTimer = 0;
        showPageToast("\u8BD1\u6587\u5DF2\u9690\u85CF\uFF0C\u70B9\u5F39\u7A97\u91CC\u7684\u300C\u663E\u793A\u8BD1\u6587\u300D\u968F\u65F6\u627E\u56DE\u3002", false);
        return;
      }
      if (pageState.enabled) {
        showPageToast("\u8BD1\u6587\u5DF2\u6062\u590D\u663E\u793A\u3002", false);
        scheduleContinuousPageTranslation(400);
      }
    }
    function startContinuousPageTranslation() {
      if (pageObserver || !document.body) {
        return;
      }
      pageObserver = new MutationObserver(() => {
        scheduleContinuousPageTranslation(500);
      });
      pageObserver.observe(document.body, {
        childList: true,
        subtree: true,
        characterData: true
      });
    }
    function stopContinuousPageTranslation() {
      if (pageObserver) {
        pageObserver.disconnect();
        pageObserver = null;
      }
      window.clearTimeout(pageTranslateTimer);
      pageTranslateTimer = 0;
    }
    function runPageScan(options = {}) {
      if (pageScanPromise || !pageState.enabled || pageState.cancelled) {
        return pageScanPromise;
      }
      pageScanPromise = scanAndTranslateMore(options).catch((error) => {
        pageState.busy = false;
        showPageToast(toReadableError(error), false);
      }).finally(() => {
        pageScanPromise = null;
      });
      return pageScanPromise;
    }
    function scheduleContinuousPageTranslation(delay = 450) {
      if (!pageState.enabled || pageState.cancelled || pageState.paused || document.hidden || pageTranslationsHidden) {
        return;
      }
      window.clearTimeout(pageTranslateTimer);
      pageTranslateTimer = window.setTimeout(() => {
        runPageScan();
      }, delay);
    }
    function togglePageToastCollapsed() {
      pageToastCollapsed = !pageToastCollapsed;
      applyPageToastState();
    }
    function dismissPageToast() {
      pageToastDismissed = true;
      hidePageToast();
    }
    function hidePageToast() {
      if (pageToast) {
        pageToast.style.display = "none";
      }
    }
    function applyPageToastState() {
      if (!pageToast) {
        return;
      }
      pageToast.classList.toggle("is-collapsed", pageToastCollapsed);
      pageToast.classList.toggle("is-positioned", Boolean(pageToastPosition));
      pageToast.classList.toggle("is-paused", pageState.paused);
      pageToast.style.setProperty("--progress", `${getPageProgressPercent()}%`);
      const ringText = pageToast.querySelector(".toast-ring span");
      if (ringText) {
        ringText.textContent = `${getPageProgressPercent()}%`;
      }
      const collapseButton = pageToast.querySelector(".collapse-page-toast");
      if (collapseButton) {
        collapseButton.textContent = pageToastCollapsed ? "\u5C55\u5F00" : "\u6536\u8D77";
        collapseButton.title = pageToastCollapsed ? "\u5C55\u5F00" : "\u6536\u8D77";
      }
      if (pageToastPosition) {
        pageToast.style.left = `${pageToastPosition.left}px`;
        pageToast.style.top = `${pageToastPosition.top}px`;
        pageToast.style.bottom = "auto";
        pageToast.style.transform = "none";
      } else {
        pageToast.style.left = "50%";
        pageToast.style.top = "";
        pageToast.style.bottom = "18px";
        pageToast.style.transform = "translateX(-50%)";
      }
    }
    function getPageProgressPercent() {
      if (!pageState.total) {
        return 0;
      }
      return Math.max(0, Math.min(100, Math.round(pageState.translated / pageState.total * 100)));
    }
    function startPageToastDrag(event) {
      if (!pageToast) {
        return;
      }
      event.preventDefault();
      event.stopPropagation();
      event.currentTarget?.setPointerCapture?.(event.pointerId);
      const rect = pageToast.getBoundingClientRect();
      pageToastDrag = {
        offsetX: event.clientX - rect.left,
        offsetY: event.clientY - rect.top
      };
      pageToast.classList.add("is-positioned");
      document.addEventListener("pointermove", movePageToast, true);
      document.addEventListener("pointerup", endPageToastDrag, true);
    }
    function movePageToast(event) {
      if (!pageToastDrag || !pageToast) {
        return;
      }
      const rect = pageToast.getBoundingClientRect();
      const left = clamp(event.clientX - pageToastDrag.offsetX, 8, window.innerWidth - rect.width - 8);
      const top = clamp(event.clientY - pageToastDrag.offsetY, 8, window.innerHeight - rect.height - 8);
      pageToastPosition = { left, top };
      applyPageToastState();
    }
    function endPageToastDrag() {
      pageToastDrag = null;
      document.removeEventListener("pointermove", movePageToast, true);
      document.removeEventListener("pointerup", endPageToastDrag, true);
    }
    function showPageToast(text, busy, options = {}) {
      ensureDom();
      if (options.force) {
        pageToastDismissed = false;
      }
      if (pageToastDismissed) {
        return;
      }
      window.clearTimeout(showPageToast.timer);
      applyPageToastState();
      pageToast.classList.toggle("is-error", Boolean(options.error));
      pageToastText.textContent = text;
      pageToast.style.display = "flex";
      const pauseButton = pageToast.querySelector(".pause-page");
      const resumeButton = pageToast.querySelector(".resume-page");
      if (pauseButton) {
        pauseButton.style.display = busy || pageState.enabled && !pageState.paused ? "inline-flex" : "none";
      }
      if (resumeButton) {
        resumeButton.style.display = pageState.paused ? "inline-flex" : "none";
      }
      if (!busy && !pageState.enabled && !pageState.paused) {
        showPageToast.timer = window.setTimeout(() => {
          if (!pageState.busy && pageToast) {
            pageToast.style.display = "none";
          }
        }, 3200);
      }
    }
    async function copyResult() {
      const text = resultNode?.textContent || "";
      if (!text) {
        return;
      }
      try {
        await navigator.clipboard.writeText(text);
        statusNode.textContent = "\u5DF2\u590D\u5236";
      } catch {
        statusNode.textContent = "\u590D\u5236\u5931\u8D25";
      }
    }
    function isInsideTranslator(target) {
      return Boolean(host && (target === host || host.contains(target)));
    }
  })();
})();
